                            # TRAVELS 
# T_1 = "Train travel"
# T_2 = "Bus travel"
# T_3 = "Flight travels"

# def location ():
#     s1 = "kanyakumari to chennai"==1 
#     s2 = "nagarkovil to chennai"==2
#     s3 = "tirunelveli to chennai"==3
a = input("kanyakumari to chennai==1,nagarkovil to chennai=2,tirunelveli to chennai==3*************************pls enter correct location of num :")
print(a)
    